#:kivy 2.0.0
<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        spacing: 20
        padding: 20
        Button:
            text:"Hello World"
        Button:
            text:"Hello World"
        Button:
            text:"Hello World"
            pos_hint: {'center_x':0.5}
            size_hint: (0.5,0.5)
            #size_hint: (None, None)
            #width: 250
            #height: 50