#:kivy 2.0.0
#: import utils kivy.utils
<MyGridLayout>

    GridLayout:
        cols:2
        size: root.width, root.height
        Button:
            text:"Hex Method"
            background_normal: ''
            background_color: utils.get_color_from_hex(root.color)
            color: utils.get_color_from_hex("#000000")
        Button:
            text:"RGBA Method"
            background_normal: ''
            background_color: (28/255.0,10/255.0,0/255.0,1)
            